# Generated by Django 6.0 on 2025-12-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='docs/')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Reviewed', 'Reviewed'), ('Signed', 'Signed')], max_length=20)),
            ],
        ),
    ]
